apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}-nginx1
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: nginx1
    image: apasoft/nginx:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
