apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-sonda-svc
  {{- template "plantilla1.etiquetas"}}
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: {{.Values.nodeport}}
    protocol: TCP
